FIRST_FIELD_COLOR = (101, 67, 31)
SECOND_FIELD_COLOR = (0, 0, 0)
BOARD_BACKGROUND_COLOR = (255, 255, 255)
CHESS_BOARD_BORDER_COLOR = (0, 0, 0)
FONT_COLOR = (0, 0, 0)
CHESS_BOARD_BORDER_SIZE = 3
FONT_SIZE = 25

WINDOW_WIDTH = 540
WINDOW_HEIGHT = 540
CHESS_BOARD_WIDTH = 480
CHESS_BOARD_HEIGHT = 480

CHESS_BOARD_WIDTH_PADDING = (WINDOW_WIDTH - CHESS_BOARD_WIDTH)/2
CHESS_BOARD_HEIGHT_PADDING = (WINDOW_HEIGHT - CHESS_BOARD_HEIGHT)/2

CHESS_FIELD_LENGHT = 60
NUMBER_OF_ROWS_ON_CHESS_BOARD = 8
NUMBER_OF_COLS_ON_CHESS_BOARD = 8